### ISSUE TITLE
How can we implement same in fragment ?

### ISSUE THREAD

**Issue by rasik1010** [AdilSoomro/Raised-Center-Tab-in-Android#2]
i want to use same layout but in fragment not in activity is this possible ? if there then can you guide me how to implement ? thanks

**Comment by AdilSoomro** [comment]
Indeed you can, I've another sample for tab and fragments. You need to take out the concept of raised center from this repo and merge it with this repo: [Iphone-Tab-in-Android](https://github.com/AdilSoomro/Iphone-Tab-in-Android)
